### ISSUE TITLE
网页编码错误

### ISSUE THREAD

**Issue by ShiinaRinne** [traceless/alist-encrypt#1]
我在`config.json`中配置了`/baidu/ym-encrypt`为加密目录，首次点进该目录时显示正常，f12的请求中只有请求源地址的两个`list`
![image](https://user-images.githubusercontent.com/45081750/226791022-e3d3f2d9-4b92-41ae-b046-cc3444dc34eb.png)

当在这个页面刷新时，网页会出现乱码，其他文件夹没有这个问题
![image](https://user-images.githubusercontent.com/45081750/226790290-fa4f156c-f2fa-443c-b571-a73f9229f903.png)
![image](https://user-images.githubusercontent.com/45081750/226792552-10c2cef9-4496-439c-95fb-c5023a2724cb.png)

**Comment by traceless** [comment]
> 我在`config.json`中配置了`/baidu/ym-encrypt`为加密目录，首次点进该目录时显示正常，f12的请求中只有请求源地址的两个`list` ![image](https://user-images.githubusercontent.com/45081750/226791022-e3d3f2d9-4b92-41ae-b046-cc3444dc34eb.png)
> 
> 当在这个页面刷新时，网页会出现乱码，其他文件夹没有这个问题 ![image](https://user-images.githubusercontent.com/45081750/226790290-fa4f156c-f2fa-443c-b571-a73f9229f903.png)

好的，我看看是什么问题，多谢！那个config.js 。你配置的alist 是在encPath['/baidu/ym-encrypt'] 对吗？你这个应该访问 http://localhost:5344 才对吧

**Comment by ShiinaRinne** [comment]
是的，我只修改了encPath中的一个路径，这里确实也是访问的5344
只是我是通过端口转发5244和5344到本地操作的，在第一个图中请求的`list`实际上是请求的原地址`video.xxxxx.com`，而不是本地的5244，不清楚和这个有没有关系

**Comment by traceless** [comment]
> 我在`config.json`中配置了`/baidu/ym-encrypt`为加密目录，首次点进该目录时显示正常，f12的请求中只有请求源地址的两个`list` ![image](https://user-images.githubusercontent.com/45081750/226791022-e3d3f2d9-4b92-41ae-b046-cc3444dc34eb.png)
> 
> 当在这个页面刷新时，网页会出现乱码，其他文件夹没有这个问题 ![image](https://user-images.githubusercontent.com/45081750/226790290-fa4f156c-f2fa-443c-b571-a73f9229f903.png) ![image](https://user-images.githubusercontent.com/45081750/226792552-10c2cef9-4496-439c-95fb-c5023a2724cb.png)

我这边复现了，我一会儿解决下
