### ISSUE TITLE
请求兼容aliyundrive,添加自定义文件后缀功能

### ISSUE THREAD

**Issue by ykxVK8yL5L** [traceless/alist-encrypt#12]
您好，前几天fork了项目 试了下 目前如果不牵涉文件名加密的话一切正常. 开启文件名加密后，使用其他webdav挂载aliyundrive即：https://github.com/messense/aliyundrive-webdav    挂载后加密文件夹无法正常访问.其他webdav客户端正常. 另外rclone无法正常上传，使用curl上传正常.
请求添加自定义后缀名的功能.即：在配置文件里自定义后缀名的映射比如.xyz对应.mp4.这样可玩性更高😄.
感谢提供这么好的项目.

**Comment by traceless** [comment]
> 您好，前几天fork了项目 试了下 目前如果不牵涉文件名加密的话一切正常. 开启文件名加密后，使用其他webdav挂载aliyundrive即：https://github.com/messense/aliyundrive-webdav 挂载后加密文件夹无法正常访问.其他webdav客户端正常. 另外rclone无法正常上传，使用curl上传正常. 请求添加自定义后缀名的功能.即：在配置文件里自定义后缀名的映射比如.xyz对应.mp4.这样可玩性更高😄. 感谢提供这么好的项目.

嗯，可以持续关注下BUG修复请， 昨天已经修复了大部分名字加密的的bug，RClone 也支持了，上传，删除，重命名都支持了，但是webdav文件复制和移动的功能还没开发，这周会解决掉。也可以进Q群了解最新的进展。

至于文件后缀随机的问题，之前有考虑到的，代码中也有预留开关。但是这个特性一直没上，因为在网页中，使用还存在问题。比如MP4对应 txt，那么就就没法启动播放器的组件进行播放。还要评估下这个后缀的影响和实现的难度。

**Comment by traceless** [comment]
> > 嗯，可以持续关注下BUG修复请， 昨天已经修复了大部分名字加密的的bug，RClone 也支持了，上传，删除，重命名都支持了，但是webdav文件复制和移动的功能还没开发，这周会解决掉。也可以进Q群了解最新的进展。
> > 至于文件后缀随机的问题，之前有考虑到的，代码中也有预留开关。但是这个特性一直没上，因为在网页中，使用还存在问题。比如MP4对应 txt，那么就就没法启动播放器的组件进行播放。还要评估下这个后缀的影响和实现的难度。
> 
> 好的 我同步下 我主要通过github actions上传 所以 加了几个环境变量来控制配置 alist本地用还行 由于需要手动挂载 在actions里不太方便上传 建议先以其他webdav为准. 至于文件后缀，没深入看代码不太清楚是否好实现.如果文件名一次性全部加密不知是否更简单点？

嗯好的 ，能否加个联系方式，qq或者wx，我 的qq ： 3121604，有一些知识想请教下你。还有一些bug，想了解更多的信息

**Comment by traceless** [comment]
> ub actions上传 所以 加了几个环境变量来控制配置 alist本地用还行 由于需要手动挂载 在actions里不太方便上传 建议先

嗯好的，我晚点注册加一下tg群。目前是按alist网页版优先的。关于你说的其他的webdav，名字加密那块还没验证，应该缺失的，应该存在你说的问题，我晚点修复一下哈，问题不大。到时候通知你
