### ISSUE TITLE
将文件从未加密的存储复制到加密的存储，文件无法在线浏览

### ISSUE THREAD

**Issue by JniTaim** [traceless/alist-encrypt#18]
测试：将文件(视频、图片)从本地存储(未加密的文件夹)复制到天翼云盘(加密的文件夹)。
将文件从未加密的存储复制到加密的存储，文件无法在线浏览，而官方客户端可以正常在线浏览。

**Comment by traceless** [comment]
> 测试：将文件(视频、图片)从本地存储(未加密的文件夹)复制到天翼云盘(加密的文件夹)。 将文件从未加密的存储复制到加密的存储，文件无法在线浏览，而官方客户端可以正常在线浏览。

因为未加密的文件直接复制过去到加密文件夹是不会自动加密的，当然就无法播放了，就是普通的移动复制。
