### ISSUE TITLE
上传的文件没有成功加密

### ISSUE THREAD

**Issue by ShiinaRinne** [traceless/alist-encrypt#2]
我修改了`config.json`中的`encPath`：`"encPath": ["/baidu/ym-encrypt"]`
alist服务与此服务部署在服务器上，通过端口转发将5244和5344映射到本地进行操作
通过5344端口的网页打开此目录，使用网页右下角的功能进行上传之后，原视频并没有被加密，百度网盘也可以在线播放。

![image](https://user-images.githubusercontent.com/45081750/226791623-ca6dbe42-57d9-4417-b04d-134a0cdc8c79.png)
![image](https://user-images.githubusercontent.com/45081750/226791711-f5c63339-9424-45e2-9cae-cf25da49e5a1.png)
![image](https://user-images.githubusercontent.com/45081750/226792224-b9dab893-088b-494a-be45-86cf143f9518.png)
## 日志
![image](https://user-images.githubusercontent.com/45081750/226791843-57f05a24-dba2-4db5-9116-e419d32740eb.png)

**Comment by traceless** [comment]
> 我修改了`config.json`中的`encPath`：`"encPath": ["/baidu/ym-encrypt"]` alist服务与此服务部署在服务器上，通过端口转发将5244和5344映射到本地进行操作 通过5344端口的网页打开此目录，使用网页右下角的功能进行上传之后，原视频并没有被加密，百度网盘也可以在线播放。
> 
> ![image](https://user-images.githubusercontent.com/45081750/226791623-ca6dbe42-57d9-4417-b04d-134a0cdc8c79.png) ![image](https://user-images.githubusercontent.com/45081750/226791711-f5c63339-9424-45e2-9cae-cf25da49e5a1.png) ![image](https://user-images.githubusercontent.com/45081750/226792224-b9dab893-088b-494a-be45-86cf143f9518.png)
> ## 日志
> 
> ![image](https://user-images.githubusercontent.com/45081750/226791843-57f05a24-dba2-4db5-9116-e419d32740eb.png)

嗯，这个路径我应该没拦截，我现在修复一下。多谢啊

**Comment by ShiinaRinne** [comment]
挺感谢这个项目，以前倒是知道有些视频被加密，需要专用的播放器才可以播放
之前alist刚出来在使用的时候，想着如果有个类似的加密功能，不仅避免和谐，还能在线看，比单纯的对文件加密压缩存储更棒。
只是技术力不足，不知道怎么下手去做，今天终于看到了这个，直接就从床上爬起来开电脑了xd

**Comment by traceless** [comment]
> 

嗯 其实实现都很简单，但是这个加密算法安全性一般，理论上容易被破解，但是对付网盘当然是没问题，他们也不可能去费劲破解这些文件。但是我觉得还能更好一些，我可能还要升级一下算法的实现，还在思考怎么去增加下破解的难度。

这个项目后续会更加完善，目前建议体验下，后续等算法确定下来，就可以生产使用了😄

**Comment by laopaoer-wallet** [comment]
@traceless 我也遇到同样的问题啦..

![image](https://user-images.githubusercontent.com/75466368/226814373-5f729abc-1b56-4c0e-80ba-70e082c6b7e9.png)
![image](https://user-images.githubusercontent.com/75466368/226814385-9ceb96f4-3759-4c8d-81da-1f43d83eeff9.png)
上传上去同样的..没有加密

**Comment by traceless** [comment]
> @traceless 我也遇到同样的问题啦..
> 
> ![image](https://user-images.githubusercontent.com/75466368/226814373-5f729abc-1b56-4c0e-80ba-70e082c6b7e9.png) ![image](https://user-images.githubusercontent.com/75466368/226814385-9ceb96f4-3759-4c8d-81da-1f43d83eeff9.png) ![image](https://user-images.githubusercontent.com/75466368/226814554-f2fbdde6-4844-49d4-a2cb-c0f2d2cfb4f5.png)
> 
> 上传上去同样的..没有加密

嗯 已经解决了，我代码上传了，目前还是有很多工作需要适配alist才行 @ShiinaRinne

**Comment by laopaoer-wallet** [comment]
@traceless 同步push下docker啊..我的好大哥 我在等着您呢

**Comment by traceless** [comment]
> @traceless 同步push下docker啊..我的好大哥 我在等着您呢

好了push 了，先体验下把，还有很多东西需要修复。。

**Comment by laopaoer-wallet** [comment]
@traceless 确实加密成功了..但是..       http://localhost:5344/aliyun/test 刷新页面 就出现乱码
![image](https://user-images.githubusercontent.com/75466368/226822159-58629617-7b49-44fc-b162-5ca3b9c2ce21.png)

**Comment by traceless** [comment]
> @traceless 确实加密成功了..但是.. http://localhost:5344/aliyun/test 刷新页面 就出现乱码 ![image](https://user-images.githubusercontent.com/75466368/226822159-58629617-7b49-44fc-b162-5ca3b9c2ce21.png)

是的，这个还要晚点修复，你从跟目录重新进来这里就好了。

**Comment by laopaoer-wallet** [comment]
![Uploading image.png…]()
也能播放加密文件了  @traceless 感谢我的好大哥

**Comment by traceless** [comment]
@ShiinaRinne  @laopaoer-wallet  页面刷新可以了，已经修复。

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/227412006-c06ded5d-b43a-4d5e-8352-16be22197d93.png)

![image](https://user-images.githubusercontent.com/45081750/227411966-3a2b354c-42be-4599-9321-11e2db0af8cb.png)

emmm是我操作不对吗，已经拉取了最新的版本，但通过右下角upload之后仍然没用，现在是只支持客户端吗
f12看到上传文件的put请求是原服务 `xx.com/api/fs/put` 而不是5344的

**Comment by traceless** [comment]
> ![image](https://user-images.githubusercontent.com/45081750/227412006-c06ded5d-b43a-4d5e-8352-16be22197d93.png)
> 
> ![image](https://user-images.githubusercontent.com/45081750/227411966-3a2b354c-42be-4599-9321-11e2db0af8cb.png)
> 
> emmm是我操作不对吗，已经拉取了最新的版本，但通过右下角upload之后仍然没用，现在是只支持客户端吗 f12看到上传文件的put请求是原服务 `xx.com/api/fs/put` 而不是5344的

我搞个q 群吧： 422035582 ，不然沟通起来 有点麻烦。我换了新RC4算法，安全性已经没问题了。
