### ISSUE TITLE
是否可以考虑解密在客户端执行

### ISSUE THREAD

**Issue by theLastWinner** [traceless/alist-encrypt#20]
目前测试发现一个问题，解密的速度比较慢，也受限于服务器带宽。是否可以考虑解密直接在客户端做，客户端直接调用对应网盘的能力，拿到数据之后，再进行解密。这样可以把数据传输放在客户端，而不会都放在服务器。

**Comment by traceless** [comment]
> 目前测试发现一个问题，解密的速度比较慢，也受限于服务器带宽。是否可以考虑解密直接在客户端做，客户端直接调用对应网盘的能力，拿到数据之后，再进行解密。这样可以把数据传输放在客户端，而不会都放在服务器。

额，本来就是推荐你在客户端部署encrypt，比如你安卓 使用autojs,  termux , dnodejs 部署 alist-encrypt 。如果是家里，或者公司，可以找个便宜的设备，arm盒子之类的部署起来就可以了，然后浏览器和webdav客户端访问这个设备IP 就好了。

**Comment by theLastWinner** [comment]
> > 目前测试发现一个问题，解密的速度比较慢，也受限于服务器带宽。是否可以考虑解密直接在客户端做，客户端直接调用对应网盘的能力，拿到数据之后，再进行解密。这样可以把数据传输放在客户端，而不会都放在服务器。
> 
> 额，本来就是推荐你在客户端部署encrypt，比如你安卓 使用autojs, termux , dnodejs 部署 alist-encrypt 。如果是家里，或者公司，可以找个便宜的设备，arm盒子之类的部署起来就可以了，然后浏览器和webdav客户端访问这个设备IP 就好了。

我刚刚手机搞了一个termux，然后打开视频还是很慢，一开始有几MB的速率在加载视频，然后一直没有播放出来。要等较久的时间才会把视频打开。我后面看看换个视频试试看。感谢回复。

**Comment by theLastWinner** [comment]
好的，谢谢。
