### ISSUE TITLE
登录密码是否可配置？

### ISSUE THREAD

**Issue by theLastWinner** [traceless/alist-encrypt#21]
目前登录密码是默认123456，是否可以设置成配置项？类似拉取docker下来，要改密码会比较麻烦。

**Comment by traceless** [comment]
> 目前登录密码是默认123456，是否可以设置成配置项？类似拉取docker下来，要改密码会比较麻烦。

首页不是有一个地方 可以修改admin 密码吗？

**Comment by theLastWinner** [comment]
> > 目前登录密码是默认123456，是否可以设置成配置项？类似拉取docker下来，要改密码会比较麻烦。
> 
> 首页不是有一个地方 可以修改admin 密码吗？

哦，忘记注意了。谢谢哈。
