### ISSUE TITLE
不支持最新版的alist

### ISSUE THREAD

**Issue by telll1** [traceless/alist-encrypt#25]
搭了半天，尝试了下别人3.12.2的alist才成功，猜测不支持最新版3.19.0的alist

**Comment by traceless** [comment]
@telll1 多谢支持，我现在抓紧去修复他

**Comment by greatbody** [comment]
应该是已经支持了，这个可以关掉了。

**Comment by greatbody** [comment]
@traceless 可以关掉这个 issue 了。
