### ISSUE TITLE
文本预览显示没有解密

### ISSUE THREAD

**Issue by Blankeer** [traceless/alist-encrypt#3]
文本预览还是乱码

<img width="699" alt="image" src="https://user-images.githubusercontent.com/8948303/227469932-3d3906dc-df65-4ebc-b275-aa5ae0adf24a.png">

**Comment by traceless** [comment]
> 文本预览还是乱码
> 
> <img alt="image" width="699" src="https://user-images.githubusercontent.com/8948303/227469932-3d3906dc-df65-4ebc-b275-aa5ae0adf24a.png">

你好，因为项目前期会有比较多的问题，可以加个群：422035582，这样讨论方便一些

**Comment by Blankeer** [comment]
有微信群吗，qq 几百年不上去一次。
感谢开源

**Comment by traceless** [comment]
> 有微信群吗，qq 几百年不上去一次。 感谢开源

嗯好的，7天有效
<img width="157" alt="图片" src="https://user-images.githubusercontent.com/4156885/227482350-b0c6c75f-434f-4729-9190-a85ade92f042.png">

**Comment by GhostKeith** [comment]
> 

QQ加群了，麻烦同意一下
