### ISSUE TITLE
针对webdav做加解密

### ISSUE THREAD

**Issue by wangdashuaihenshuai** [traceless/alist-encrypt#38]
感觉可以只针对alist 的/dav 路径的webdav接口做加解密就行了，可以少很多适配不同网盘的工作量。

**Comment by traceless** [comment]
> 感觉可以只针对alist 的/dav 路径的webdav接口做加解密就行了，可以少很多适配不同网盘的工作量。

目前是支持对webdav进行配置的，你也可以单独添加alist的webdav配置就可以哦。这个也是同时支持对alist 网页版本的兼容。
