### ISSUE TITLE
与 rclone crypt 的兼容性？

### ISSUE THREAD

**Issue by BakaJzon** [traceless/alist-encrypt#39]
我想将rclone的加密功能转到这个项目，对于那些被rclone加密的项目，我是否可以直接通过alist-encrypt加解密呢？

**Comment by traceless** [comment]
> 我想将rclone的加密功能转到这个项目，对于那些被rclone加密的项目，我是否可以直接通过alist-encrypt加解密呢？

可以啊，新增这个rclone的加解密 也很好啊，最近没时间写这个rclone的加解密哦，你能帮忙新增一个吗

**Comment by BakaJzon** [comment]
话说alist本体已经加了加密功能了:cry:<https://alist.nn.ci/zh/guide/drivers/Crypt.html>

**Comment by traceless** [comment]
> 话说alist本体已经加了加密功能了😢https://alist.nn.ci/zh/guide/drivers/Crypt.html

哈哈😄， 是啊，他们用的是rclone 的加解密，好像是兼容rclone，你可以试试看，我这个暂时还不能支持，我后续会兼容下来。

**Comment by BakaJzon** [comment]
其实也可以选择不兼容吧？毕竟不是什么必要的功能， alist 那边也给出了平替。
我认为没有必要，就先关了

Have a nice day~

**Comment by traceless** [comment]
> 其实也可以选择不兼容吧？毕竟不是什么必要的功能， alist 那边也给出了平替。 我认为没有必要，就先关了
> 
> Have a nice day~

嗯 👌🏻
