### ISSUE TITLE
config.js中的password是明文存储，是否可以通过该密码解密数据？希望通过更安全的方式存储密码。

### ISSUE THREAD

**Issue by kaine1973** [traceless/alist-encrypt#4]
希望通过更安全的方式存储密码，比如运行时config.js读取环境变量ALIST_ENC_PASSWORD作为密码？

**Comment by traceless** [comment]
> 希望通过更安全的方式存储密码，比如运行时config.js读取环境变量ALIST_ENC_PASSWORD作为密码？

嗯，这边可以设置多个文件夹不同的密码的，所以如果觉得明文不方便的话，后续会写到数据库中。

**Comment by qzane** [comment]
感觉这个很重要啊，在公共服务器上明文存密码太不安全了，希望能早点实现。
