### ISSUE TITLE
感觉好慢？

### ISSUE THREAD

**Issue by KnIfER** [traceless/alist-encrypt#49]
测试了一个大文件
800mb的MP4，不算太大，挂载本机存储。本地浏览器播放是秒出的。
然而局域网（wifi）就需要缓存 8 秒，同样环境下，原5244只需缓存 2 秒。

挂载云盘也要缓存5~8秒。

是加密方式太复杂，还是需要处理的数据量大？

**Comment by traceless** [comment]
> 测试了一个大文件 800mb的MP4，不算太大，挂载本机存储。本地浏览器播放是秒出的。 然而局域网（wifi）就需要缓存 8 秒，同样环境下，原5244只需缓存 2 秒。
> 
> 挂载云盘也要缓存5~8秒。
> 
> 是加密方式太复杂，还是需要处理的数据量大？

(⊙o⊙)…不会的啊，armv8 盒子随便可以跑满500Mbps的。网友测试30G的阿里云电影都可以秒播放。你那边部署的机器是什么呢？

**Comment by KnIfER** [comment]
破wifi + 普通安卓，alist在电脑上。

数据量大的话，我觉得无需过度加密，又不是真的机密蚊件。。
如果只加密文件头，或者偏移数据，会不会更快一些？

**Comment by KnIfER** [comment]
不解密，直接代理是秒开的，播发器打开的是5344代理的redirect。

```
  let decryptTransform = ...
  if (decode) {
    decryptTransform = decode !== '0' ? flowEnc.decryptTransform() : null
  }
  decryptTransform  = null;
  // 请求实际服务资源
```

**Comment by traceless** [comment]
> 破wifi + 普通安卓，alist在电脑上。
> 
> 数据量大的话，我觉得无需过度加密，又不是真的机密蚊件。。 如果只加密文件头，或者偏移数据，会不会更快一些？

这个加密就是AES-CTR加密，速度是很快的，哪怕50元的电视盒子都能跑的快。你那边是什么网盘，我来试试看。你也可以测试一下阿里云盘或者天翼云盘试试速度。

**Comment by KnIfER** [comment]
就是本机存储。阿里云盘也试过了。

不过我就试过一个大的视频文件加密，空间不多。。

**Comment by traceless** [comment]
> 就是本机存储。阿里云盘也试过了。
> 
> 不过我就试过一个大的视频文件加密，空间不多。。

方便加个联系方式，q: 312160四 ，或者你进群私聊我。我帮你看看什么原因。或者你用电脑的方式部署encrypt 看看速度。

**Comment by KnIfER** [comment]
ffmpeg -i input.mp4 -movflags +faststart -acodec copy -vcodec copy output.mp4
