### ISSUE TITLE
后台admin密码忘记了，如何找回？

### ISSUE THREAD

**Issue by drw2005** [traceless/alist-encrypt#72]
试了很多次，一时半会想不起来了，请教大佬如何找回或者重置？
谢谢！

**Comment by drw2005** [comment]
想起密码了。

**Comment by traceless** [comment]
> 试了很多次，一时半会想不起来了，请教大佬如何找回或者重置？ 谢谢！

这个密码是没办法的找回的，但是可以在配置文件中查看到，有一个config.json 文件。一般来说密码其实不重要，推荐简单密码即可。因为加密的本质是防止被扫描。网盘的密码才是你的文件安全的重要保障，这个加密跟你的手机锁屏密码 差不多就好了。
